default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { ENV['sliucc_DATABASE_PASSWORD'] } %>
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>

development:
  <<: *default
  database: sliucc_development

test:
  <<: *default
  database: sliucc_test

production:
  <<: *default
  database: sliucc_production
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>